### ISSUE TITLE
Background Save Hangs. Prevents Subsequent Saves

### ISSUE THREAD

**Issue by m4g005** [RedisGraph/RedisGraph#599]
Symptom: Configured bgsave does not complete and prevents persisting further changes.
This has only occurred with RedisGraph, so posting here.

```
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4d0898999c5f857
redis_mode:standalone
os:Linux 3.10.0-862.11.6.el7.x86_64 x86_64
```

We are running the service in a docker container, graph module version `19900`.

Here are the logs:

```
1:M 28 Jul 2019 02:23:26.049 * 10 changes in 300 seconds. Saving...
1:M 28 Jul 2019 02:23:26.103 * Background saving started by pid 74
74:C 28 Jul 2019 02:23:37.722 * DB saved on disk
74:C 28 Jul 2019 02:23:37.766 * RDB: 53 MB of memory used by copy-on-write
1:M 28 Jul 2019 02:23:37.840 * Background saving terminated with success
1:M 28 Jul 2019 02:28:38.057 * 10 changes in 300 seconds. Saving...
1:M 28 Jul 2019 02:28:38.111 * Background saving started by pid 75
1:signal-handler (1565826580) Received SIGTERM scheduling shutdown...
@@@1:M 14 Aug 2019 23:49:41.404 # User requested shutdown...
1:M 14 Aug 2019 23:49:41.484 # There is a child saving an .rdb. Killing it!
1:M 14 Aug 2019 23:49:41.616 * Saving the final RDB snapshot before exiting.
1:C 15 Aug 2019 04:00:38.624 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
```

This caused data loss from 7/28, _however_ the graph operated normally during this time period.

Is there a way to stop the background save?
Is there a way to find out why a bgsave is hung?

We suspect that there is something in the data being persisted, but not really sure where to start in looking for it.

**Comment by jeffreylovitz** [comment]
@m4g005 I'm very sorry this happened! We're not aware of any issues with RedisGraph's current persistence routines, which have changed little in the past several months. As you suspect, it seems likeliest that something in your data or a modification made to the graph caused our serializer to hang.

 We'll prioritize fixing this, but need some further details about your environment and data in order to proceed.

Environment information:
1) Did you pull a specific tag (such as `edge`) of the RedisGraph Docker image or use the default?
2) Are any of your configurations different than the Redis defaults? (If so, sharing them would be a great help!)
3) Are you using any form of replication on your server?
4) Have you encountered any out-of-memory errors on your server?

Graph information:
1) Have you run queries that delete nodes, edges, or properties from the graph?
2) Does any of your stored data include binary strings or special characters?
3) Do you have multiple edges of the same type connecting the same source and destination nodes?

None of these cases _should_ cause problems in serialization, but might help us narrow down the problem. Any details or samples of your data and/or queries would be helpful in diagnosing the issue, but I understand you may not be free to share them.

In the future, you can use the `info persistence` command to see if a bgsave is hanging - `rdb_bgsave_in_progress` will be set to 1.

I would recommend using the [dump](https://redis.io/commands/dump) command to attempt to save your graph key. You can also kill the hanging process without risk to your server provided that you have the pid. Your log indicates that the hanged PID is 75, so `kill -9 75` would accomplish this. (Depending on your configuration, you might have to run `config set stop-writes-on-bgsave-error no` after this.)

If the server logs don't have any information about the hanging process, I don't believe there is a standard way to introspect about the problem further, though you can use `gdb` to attach to the hanging process and possibly get some information that way.

**Comment by m4g005** [comment]
Thanks for the response! We'll get going on using your suggestions to troubleshoot. It turns out, three of our systems were in this state and seemed to have this commonality: They were all in an extended period of heavy Read/Write/Delete from a running process (an import that potentially removed data in addition to adding). Our automatic save was configured for every 5 minutes when 10 or more changes. There were very likely A LOT more changes than 10. Other information your requested:

> Did you pull a specific tag (such as edge) of the RedisGraph Docker image or use the default? 

It was `latest` from a few weeks ago (not sure atm how to tell you exactly which image it was)

> Are any of your configurations different than the Redis defaults? (If so, sharing them would be a great help!)

Default configs

> Are you using any form of replication on your server?

No

> Have you encountered any out-of-memory errors on your server?

Not in this particular environment and it has plenty of head room

> Does any of your stored data include binary strings or special characters?

No binary strings. The only special characters we might expect are sorta standard: E.g., apostrophes that might go into string data (this is not to say that unexpected special characters could exist, but we don't know about them -- we don't directly control the data source)

> Do you have multiple edges of the same type connecting the same source and destination nodes?

No

Since we've identified what we think was going on when this happened, I can try and reproduce the problem. Let me know if you have any further questions and I'll report back with any findings.

**Comment by m4g005** [comment]
Was able to reproduce the issue. I killed the process and the bgsaves started up again.
This happened during high volatility in the graph -- I believe that > 5000 nodes were being dropped and recreated. But that sort of thing had happened a few times at least already.

I will see if I can zero in on specific data that is doing it next.

**Comment by swilly22** [comment]
@m4g005, we believe we've figured this one out,

RedisGraph utilize read/write locks,
assume a write query comes a long and acquires the write lock, (no readers can enter) at that time Redis performs BGSave by forking a new process which is both write locked and might have some inconsistent graph data.

For us to perform data dumping we are required to acquire the read lock which causes the forked process to dead lock as releases to that lock won't reach it.

Currently we've got a number of alternative we would like to explore, we'll update here on our progress, for the time-being I'll suggest avoiding using BG-Save.

**Comment by m4g005** [comment]
Thanks! We will avoid bgsave for our import process and be a bit more judicious with it in general.

**Comment by jeffreylovitz** [comment]
Hi @m4g005,

We've added some safeguards to our `bgsave` handling, so this issue should be solved, and you can return to your standard workflow!

The fix has been merged into master, so it's accessibly be building from source or using the Docker tag `edge`.

**Comment by m4g005** [comment]
Thanks for fixing this! We'll give it a go.

For our short term, we've disabled the bgsave for importing and then turn it back on for regular operations.

FWIW: you might provide some guidance somewhere on best practices for persisting data since (per [575](https://github.com/RedisGraph/RedisGraph/issues/575)) appendonly does not work (something else we figured out the hard way). (I realize you probably have tons to do, so maybe at minimum people will see this and the other issue)

**Comment by jeffreylovitz** [comment]
Hm, how was the server instantiated when you had `appendonly` turned on? We try to foreground that limitation as best as possible:
```
$ redis-server --appendonly yes --loadmodule src/redisgraph.so
7079:C 04 Sep 2019 09:13:05.911 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7079:C 04 Sep 2019 09:13:05.911 # Redis version=5.0.5, bits=64, commit=c696aebd, modified=1, pid=7079, just started
7079:C 04 Sep 2019 09:13:05.911 # Configuration loaded
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 5.0.5 (c696aebd/1) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 7079
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

7079:M 04 Sep 2019 09:13:05.912 # Server initialized
7079:M 04 Sep 2019 09:13:05.913 # <graph> RedisGraph does not support AOF
7079:M 04 Sep 2019 09:13:05.913 # Module src/redisgraph.so initialization failed. Module not loaded
7079:M 04 Sep 2019 09:13:05.913 # Can't load module from src/redisgraph.so: server aborting
```
The no-AOF limitation should actually be lifted soon; we've written an update to Redis and are waiting for it to be backported to a stable version.

I agree that a page on best practices for persistence is a very good idea (as your experiences prove)! We'll try to augment our documentation with that soon.

**Comment by m4g005** [comment]
We start the service with Ansible (in a docker container) so never see this message.
Part of the problem I had was that I didn't spend the extra 5 minutes reading about setting AOF at startup, so yeah, reading is fundamental.

Thanks again for all of your work!

**Comment by daveb1976** [comment]
Hi. We are still experiencing this issue regularly. We thought it might be down to headroom on the docker pod radiograph was running on, but we have just recreated the issue on a next-to-empty graph with loads of headroom.

Here you can see the problem:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/218959/132646375-3db1cd46-7b0c-40a3-88d8-babc8892671c.png">

This is the impact on memory on the POD. You can also see that we're no-where near any memory limits.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/218959/132646516-30187f92-8214-4f17-83b2-35cf35a1d1dc.png">

You can see the hung process (197624) here:
```
find /proc -mindepth 2 -maxdepth 2 -name exe -exec ls -lh {} \; 2>/dev/null
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/1/exe -> /usr/local/bin/redis-server
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/10345/exe -> /bin/bash
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/12103/exe -> /bin/bash
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/14189/exe -> /bin/bash
lrwxrwxrwx 1 redis redis 0 Sep  8 15:30 /proc/32582/exe -> /usr/local/bin/redis-cli
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/197624/exe -> /usr/local/bin/redis-server
lrwxrwxrwx 1 redis redis 0 Sep  9 07:50 /proc/882510/exe -> /usr/bin/find
```

Our remedy is to `kill -9 197624` which causes redid to retry the save. Typically on retry the save works correctly.

**Comment by swilly22** [comment]
@daveb1976 can you provide steps to recreate ?

**Comment by swilly22** [comment]
@daveb1976 I've been able to reproduce a fix should be available shortly

**Comment by daveb1976** [comment]
@swilly22 - this is awesome news - thank you very much.

**Comment by swilly22** [comment]
@daveb1976 fix just been merged, should be ~2hours before dockerhub is updated, would you be able to validate things on your end?

**Comment by daveb1976** [comment]
Yes, absolutely

**Comment by daveb1976** [comment]
Hi @swilly22. We're trying to test this and are now getting an immediate error with replication.

```
redis-graph-replica-5fcb4bf7d-6gfzf redis-graph === REDIS BUG REPORT START: Cut & paste starting from here ===
redis-graph-replica-5fcb4bf7d-6gfzf redis-graph 1:S 13 Sep 2021 13:53:03.527 # ------------------------------------------------
redis-graph-replica-5fcb4bf7d-6gfzf redis-graph 1:S 13 Sep 2021 13:53:03.527 # !!! Software Failure. Press left mouse button to continue
redis-graph-replica-5fcb4bf7d-6gfzf redis-graph 1:S 13 Sep 2021 13:53:03.527 # Guru Meditation: Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphmeta' after reading '0' bytes of a value for key named: '{HMS}HMS_e6b62f9e-0d34-4465-bb92-eef7e4914f44'. #module.c:4614
```

**Comment by daveb1976** [comment]
@swilly22 

This looks really positive. It's the same load that was causing the `bgsave` hang repeatedly and has now completed without issues. 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/218959/133134016-780b2944-395f-492a-a069-c315921e724d.png">

I'll do some more testing on the replication side of things and raise another issue if necessary. But the `bgsave` issue appears resolved at this stage.

Thanks for your quick turnaround!

**Comment by swilly22** [comment]
awesome, please feel free to close this issue when you feel comfortable, if there's an issue with the replication link let's handle that on a separated issue.

**Comment by daveb1976** [comment]
@swilly22, I don't think I have rights to close the issue I'm afraid. Happy to though.
